// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebApplication.Data;

namespace TestWebApplication.Data.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20211030101149_Has6Data")]
    partial class Has6Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWebApplication.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 22,
                            Bio = "",
                            Gender = false,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Bio = "",
                            Gender = true,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            Bio = "",
                            Gender = false,
                            Name = "Ivy"
                        },
                        new
                        {
                            Id = 4,
                            Age = 27,
                            Bio = "",
                            Gender = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            Age = 31,
                            Bio = "",
                            Gender = true,
                            Name = "Chief"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
